### ISSUE TITLE
Is there a CSS framework we should be using?

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/optimism#12]
Obviously we'll be making the pages look awesome.  Is there a particular CSS framework we should use as a base for it?  @zarino, do you have a go-to option for that?

**Comment by amcewen** [comment]
Bootstrap would be the default-developer choice.  I've also seen https://bulma.io/ but haven't used it (yet).

**Comment by zarino** [comment]
@amcewen beat me to it. Yes, my vote would be for Bootstrap too. It’s pretty much an industry standard, and the docs are very approachable for newcomers, including lots of HTML markup examples that you could just lift directly if you needed to.

I’d recommend incorporating the Sass version into your project, and then compiling to CSS, as that lets you customise all the settings without adding lots of bloat.

Annoyingly, the Bootstrap team is currently right on the cusp of releasing Bootstrap 5, which will do things a bit differently to 4. The upgrade shouldn’t be too difficult though, so I’d probably stick to 4 for now, and earmark an upgrade to 5 as a project for the future ;-)

**Comment by helicalbytes** [comment]
In the most recent develop branch I've added a folder for bootstrap with a site scss file (optimism.scss) and a subfolder for version 4.5.1 bootstrap scss.

The node-sass module is also installed and commands for compiling scss added.

**Comment by amcewen** [comment]
Looking good so far!

![image](https://user-images.githubusercontent.com/108468/91898783-28ad9180-ec94-11ea-8162-3cad587aabc3.png)

I'm calling this closed.
