### ISSUE TITLE
Rework environment to have separate API and Web server apps

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/optimism#13]
In tonight's hack-the-space meeting we decided to architect things into three components: 
  * an API server
  * a web server (which calls the API server and generates server-side HTML)
  * client-side code (which can also call the API server to update things interactively, client-side code will be jQuery based - at least until our needs become such that implementing a React system makes sense)

We should rework the current code to have the two different servers.

**Comment by helicalbytes** [comment]
I have refactored the environment to have 2 projects: website and api.
Website is on port 3000
Api is on port 3001

This is in a new **develop** branch. I haven't merged this with master yet.

The api is non-functional.

The website has a few pages on it, just as an example to hopefully get us started and have something to look at and discuss. It's not meant to be a proposition for a site design.

There is a bootstrap folder for version 4.5.1, with an example scss file for the site called optimism.scss in that folder.
This compiles to the website/static/css folder as optimism.css.
(Note that in the html, the file URL is /css/optimism.css -- the 'static' part isn't needed.)

I have added a number of script commands to package.json. Maybe the most useful will be `npm run dev-all` which concurrently starts the website, api and a compiler for scss.

I have installed the nodemon package as a dev dependency. This monitors api and website code file changes and restarts the respective sites as required.

The concurrently package allows more than one command to be started concurrently with the outlet from all sent to a single terminal. That is what is used with npm run dev-all.

**Comment by helicalbytes** [comment]
Would someone be able to clone the repo, check out develop and see if they can get it to work on their system?

So basically:

`npm install`

`npm run dev-all`

Then check there's a website on localhost:3000 and something that says hello on localhost:3001.

**Comment by JackiePease** [comment]
Maybe later this eveningOn 6 Aug 2020 16:31, helicalbytes <notifications@github.com> wrote:
Would someone be able to clone the repo, check out develop and see if they can get it to work on their system?
So basically:
npm install
npm run dev-all
Then check there's a website on localhost:3000 and something that says hello on localhost:3001.

**Comment by helicalbytes** [comment]
Thanks @JackiePease.

Just for information, my node version is v12.16.1 (and npm is 6.13.4). I don't think that will matter at all, as long as you have a reasonably recent version, but just in case. I'm developing on Windows. But it works fine on Windows Subsystem For Linux (version 2) too, which uses Ubuntu 18.04 LTS.

Also, you need to run npm install and npm run dev-all after checking out the develop branch, since the master one isn't up-to-date.

**Comment by JackiePease** [comment]
Tried this - it works fine

**Comment by amcewen** [comment]
Is there anything more to do on this?  Or can we close it now that a few of us have confirmed it's working?

**Comment by helicalbytes** [comment]
Am closing this. It seems to work OK.
