### ISSUE TITLE
Create some initial data to seed the database

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/optimism#14]
Now we've got a database, and things set up, it'd be handy to have an easy way for all of us working on it generate the initial resources, etc.

That should be possible with `knex` commands.

**Comment by amcewen** [comment]
Seems that if you haven't installed the `knex` node module as a global you won't have a `knex` command available on your path.  As a workaround (I was wary of a globally installed `knex` drifting in version from the local one) you can run `node node_modules/knex/bin/cli.js` instead.

Created seeds with variations on:
```
node node_modules/knex/bin/cli.js seed:make resource_types_seed --env development
```

And populated the resulting files with data from `test-data/`

You can then populate your development database (**warning, this will delete any existing data**) by running:
```
node node_modules/knex/bin/cli.js seed:run --env development
```

I haven't done the `slots`, `resource_slots` or `bookings` yet (mostly because I haven't fully worked out how the data model for slots works.  Something to discuss on Tuesday maybe...)

**Comment by johnmckerrell** [comment]
I think this is now done, feel free to reopen if you think otherwise. We've certainly got some initial data, and a documented mechanism for importing it.
