### ISSUE TITLE
Set up optimism on organisers.doesliverpool.com

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/optimism#16]
We should delete the existing droplet and create a new one, and set this up to run on it.

**Comment by amcewen** [comment]
In order to test and flush out the last bits of dockerizing the setup in #17, this has been deployed!  http://organisers.doesliverpool.com will give you a very basic version of the site now! :tada:

**Comment by ajlennon** [comment]
ooooooooh! love it! nice work :smile:
