### ISSUE TITLE
Capture booking user details

### ISSUE THREAD

**Issue by helicalbytes** [DoESLiverpool/optimism#23]
This is what is currently step 3 of the booking process.

A user has selected their resources, dates and time by this stage and we need to collect:

- Their name
- Their email address
- Any notes they want to provide

For certain resources (example: laser cutters) we also want/need to capture whether they have had an induction, or any other training required.

![image](https://user-images.githubusercontent.com/108468/106664298-c6d3b980-659c-11eb-924d-039e150b34a4.png)

**Comment by amcewen** [comment]
It's fairly basic, for now, but there's a form to capture the relevant details.
