### ISSUE TITLE
Create GitHub actions to run tests on commit to develop branch

### ISSUE THREAD

**Issue by helicalbytes** [DoESLiverpool/optimism#32]

**Comment by amcewen** [comment]
Worked out a `Dockerfile` that runs the tests successfully this evening.  At the moment I've just modified the existing `Dockerfile` so the next step will be to create a testing-specific version that pulls in the default and then updates it for the testing side.

Then we can work out how to run it from the github actions and fail properly if one of the tests fails.

**Comment by amcewen** [comment]
To run it locally for testing:
1. `docker build . -t api-test`
2. `docker run -t api-test`

Now I've updated the `Dockerfile` in `api` to use arguments to customise it for building the testing version.

There are two arguments: `NODE_ENVIRONMENT` which defaults to `production` and should be set to `testing` for the test build; and `TEST_FOLDER`, which defaults to `no-test` (so copies an empty folder across) and should be set to `test` for the test build.  Building with no arguments (as in step 1 above) will build the production version; to build the test version run `docker build --build-arg=NODE_ENVIRONMENT=testing --build-arg=TEST_FOLDER=test -t test-api .`

Running the container starts the production server by default; to run the tests you should override the command with: `docker run --rm=true -t api-test  /home/node/app/node_modules/mocha/bin/mocha --recursive --exit --timeout 3500`

So next I need to check this in, and then get it to run whenever there's a check-in to `develop`

**Comment by amcewen** [comment]
Tested a deliberately failing test and that failed the test action correctly.  Now we just need more tests :grin:
