### ISSUE TITLE
Create test database with Knex

### ISSUE THREAD

**Issue by stuartedward** [DoESLiverpool/optimism#37]

**Comment by JackiePease** [comment]
Useful blog post here: [https://mherman.org/blog/test-driven-development-with-node/](https://mherman.org/blog/test-driven-development-with-node/)

**Comment by JackiePease** [comment]
@stuartedward and I worked on this today. We were able to set up the system to reseed the test database with additional resources. Need to investigate further how to change from test to development databases using environment variables.

**Comment by amcewen** [comment]
Reading https://gist.github.com/NigelEarle/70db130cc040cc2868555b29a0278261 is looks like you might be able to drop tables in knex with `knex.schema.dropTable('name-of-table')` (given @JackiePease and @stuartedward were looking for that t'other day)

**Comment by JackiePease** [comment]
Added lines to db.js to read in environment variable NODE_ENV for use by the API. This now picks up the testing branch. Checked in the branch.

**Comment by JackiePease** [comment]
Followed the instructions in the gist mentioned by @amcewen above to add a migration. The gist has a bug - it's missing "return" before "knex" in the Adding and Dropping Columns section.
