### ISSUE TITLE
Show list of available resources

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/optimism#5]
Note that as we link through to the booking page it would be good for it to have a canonical page rather than this being a dynamic form so that we can link directly through to https://bookings.doesliverpool.com/resources/sophia and https://bookings.doesliverpool.com/resources/events-room

(Or something along those lines)

**Comment by amcewen** [comment]
Made a start on the database models for this tonight.  There's now `src/models/resource.js`.  It doesn't do anything with the database yet, I think I need to read some more [Sequelize documentation](https://sequelize.org/v5/manual/getting-started) first.

**Comment by amcewen** [comment]
This is working now with the new system.
