### ISSUE TITLE
Pass on the selected time slot from the calendar UI to the "make a booking screen"

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/optimism#8]
Take the time slot selected by the user on the calendar UI and pass it onto the "Make a booking" page which will be completed in #23

**Comment by amcewen** [comment]
What do we do about asking them if they've had an induction for the laser-cutters?  That would only be relevant for laser-cutter or CNC room bookings, obviously...

For the first pass, we can just tell people that they need to have had an induction...

**Comment by johnmckerrell** [comment]
This now looks very similar to #23. I've rejigged this ticket to be "pass on the time slot to the booking page" and moved the screen grab over to the other ticket.

**Comment by amcewen** [comment]
As part of this we should also stop the "Provide your detail" button from being selectable until a slot has been chosen.

**Comment by amcewen** [comment]
I've made a start on this - the booking details are now passed on to the `/your-details` page, although the `start` and `finish` times aren't yet populated on the `/select-a-time` page (they exist as form variables, but nothing fills them in).

The "Provide your details" button is also always selectable - it needs to only be possible when a slot is chosen.

**Comment by amcewen** [comment]
I've finished off this so it populates the `start` and `finish` fields when a slot is chosen.  The submit button is also disabled initially, and then enabled once a slot is chosen.

I'm not 100% sure I've set the input values in the correct way - it works fine on Firefox, but felt a bit too easy :grin:  @helicalbytes, can you give https://github.com/DoESLiverpool/optimism/commit/f7c22f7a4e928947fa52c9b26194ba56c4cdc818 the once over to see if it looks okay?
